package lit

import (
	"io/ioutil"
	"strings"
)

// the version global var will be set by the make go build call.
// to read the variable by go build -ldflags it must be the type of string.

var Version = "0.3.1"

func ProcessFile(src string, remove bool) ([]byte, error) {
	inputData, err := ioutil.ReadFile(src)
	if err != nil {
		return []byte{}, err
	}

	// # process
	lines := strings.Split(string(inputData), "\n")
	// change each non code line
	for i, v := range lines {
		if v != "" {
			if !strings.HasPrefix(v, "    ") {
				if !strings.HasPrefix(v, "\t") {
					if remove {
						lines[i] = ""
					} else {
						lines[i] = "// " + v
					}
				}
			}
		}
	}

	// # output
	out := strings.Join(lines, "\n")
	outPre := "// GENERATED BY LITC v" + Version + "\n// DO NOT EDIT BY HAND\n\n"
	return []byte(outPre + out), err
}
