package lit

import (
	"fmt"
	"os"
	"testing"
)

func Test_Lit(t *testing.T) {
	d, err := ProcessFile("fixture.sh.md", false)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	expected := `// GENERATED BY LITC v` + Version + `
// DO NOT EDIT BY HAND

// # fixture data

	hello world
`
	if string(d) != expected {
		t.Error("processed result not equal")
	}

}
